/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SosmedRouteImport } from './routes/sosmed'
import { Route as SertifikatRouteImport } from './routes/sertifikat'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MateriCourseIdRouteImport } from './routes/materi.$courseId'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'

const SosmedRoute = SosmedRouteImport.update({
  id: '/sosmed',
  path: '/sosmed',
  getParentRoute: () => rootRouteImport,
} as any)
const SertifikatRoute = SertifikatRouteImport.update({
  id: '/sertifikat',
  path: '/sertifikat',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriCourseIdRoute = MateriCourseIdRouteImport.update({
  id: '/materi/$courseId',
  path: '/materi/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/jadwal': typeof JadwalRoute
  '/login': typeof LoginRoute
  '/sertifikat': typeof SertifikatRoute
  '/sosmed': typeof SosmedRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/materi/$courseId': typeof MateriCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/jadwal': typeof JadwalRoute
  '/login': typeof LoginRoute
  '/sertifikat': typeof SertifikatRoute
  '/sosmed': typeof SosmedRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/materi/$courseId': typeof MateriCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/jadwal': typeof JadwalRoute
  '/login': typeof LoginRoute
  '/sertifikat': typeof SertifikatRoute
  '/sosmed': typeof SosmedRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/materi/$courseId': typeof MateriCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/jadwal'
    | '/login'
    | '/sertifikat'
    | '/sosmed'
    | '/course/$courseId'
    | '/kategori/$slug'
    | '/materi/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/jadwal'
    | '/login'
    | '/sertifikat'
    | '/sosmed'
    | '/course/$courseId'
    | '/kategori/$slug'
    | '/materi/$courseId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/jadwal'
    | '/login'
    | '/sertifikat'
    | '/sosmed'
    | '/course/$courseId'
    | '/kategori/$slug'
    | '/materi/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  JadwalRoute: typeof JadwalRoute
  LoginRoute: typeof LoginRoute
  SertifikatRoute: typeof SertifikatRoute
  SosmedRoute: typeof SosmedRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  MateriCourseIdRoute: typeof MateriCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sosmed': {
      id: '/sosmed'
      path: '/sosmed'
      fullPath: '/sosmed'
      preLoaderRoute: typeof SosmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sertifikat': {
      id: '/sertifikat'
      path: '/sertifikat'
      fullPath: '/sertifikat'
      preLoaderRoute: typeof SertifikatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/$courseId': {
      id: '/materi/$courseId'
      path: '/materi/$courseId'
      fullPath: '/materi/$courseId'
      preLoaderRoute: typeof MateriCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  JadwalRoute: JadwalRoute,
  LoginRoute: LoginRoute,
  SertifikatRoute: SertifikatRoute,
  SosmedRoute: SosmedRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  MateriCourseIdRoute: MateriCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
