/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SertifikatRouteImport } from './routes/sertifikat'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MateriCourseIdRouteImport } from './routes/materi.$courseId'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as EventSuccessRouteImport } from './routes/event.success'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'

const SertifikatRoute = SertifikatRouteImport.update({
  id: '/sertifikat',
  path: '/sertifikat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriCourseIdRoute = MateriCourseIdRouteImport.update({
  id: '/materi/$courseId',
  path: '/materi/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSuccessRoute = EventSuccessRouteImport.update({
  id: '/event/success',
  path: '/event/success',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/login': typeof LoginRoute
  '/masuk': typeof MasukRoute
  '/profil': typeof ProfilRoute
  '/sertifikat': typeof SertifikatRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/event/success': typeof EventSuccessRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/materi/$courseId': typeof MateriCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/login': typeof LoginRoute
  '/masuk': typeof MasukRoute
  '/profil': typeof ProfilRoute
  '/sertifikat': typeof SertifikatRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/event/success': typeof EventSuccessRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/materi/$courseId': typeof MateriCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/login': typeof LoginRoute
  '/masuk': typeof MasukRoute
  '/profil': typeof ProfilRoute
  '/sertifikat': typeof SertifikatRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/event/success': typeof EventSuccessRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/materi/$courseId': typeof MateriCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/galeri'
    | '/jadwal'
    | '/login'
    | '/masuk'
    | '/profil'
    | '/sertifikat'
    | '/course/$courseId'
    | '/event/$eventId'
    | '/event/success'
    | '/kategori/$slug'
    | '/materi/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/galeri'
    | '/jadwal'
    | '/login'
    | '/masuk'
    | '/profil'
    | '/sertifikat'
    | '/course/$courseId'
    | '/event/$eventId'
    | '/event/success'
    | '/kategori/$slug'
    | '/materi/$courseId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/galeri'
    | '/jadwal'
    | '/login'
    | '/masuk'
    | '/profil'
    | '/sertifikat'
    | '/course/$courseId'
    | '/event/$eventId'
    | '/event/success'
    | '/kategori/$slug'
    | '/materi/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GaleriRoute: typeof GaleriRoute
  JadwalRoute: typeof JadwalRoute
  LoginRoute: typeof LoginRoute
  MasukRoute: typeof MasukRoute
  ProfilRoute: typeof ProfilRoute
  SertifikatRoute: typeof SertifikatRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  EventEventIdRoute: typeof EventEventIdRoute
  EventSuccessRoute: typeof EventSuccessRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  MateriCourseIdRoute: typeof MateriCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sertifikat': {
      id: '/sertifikat'
      path: '/sertifikat'
      fullPath: '/sertifikat'
      preLoaderRoute: typeof SertifikatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi/$courseId': {
      id: '/materi/$courseId'
      path: '/materi/$courseId'
      fullPath: '/materi/$courseId'
      preLoaderRoute: typeof MateriCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/success': {
      id: '/event/success'
      path: '/event/success'
      fullPath: '/event/success'
      preLoaderRoute: typeof EventSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GaleriRoute: GaleriRoute,
  JadwalRoute: JadwalRoute,
  LoginRoute: LoginRoute,
  MasukRoute: MasukRoute,
  ProfilRoute: ProfilRoute,
  SertifikatRoute: SertifikatRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  EventEventIdRoute: EventEventIdRoute,
  EventSuccessRoute: EventSuccessRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  MateriCourseIdRoute: MateriCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
